server:
  port: 7000

spring:
  application:
    name: config-server
  security:
    user:
      name: admin
      password: 123456
  cloud:
    config:
      server:
        git:
          uri: https://github.com/medwinwang/could_test/config  # 配置git仓库的地址
          searchPaths: config-repo                             # git仓库下的相对地址（多个则用半角逗号分隔）
          # username: username                                 # 只有private的项目才需配置用户名和密码
          # password: password                                 # 只有private的项目才需配置用户名和密码

eureka:
  port: 9001
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${eureka.port}/eureka/