server:
  port: 8000
spring:
  security:
    user:
        name: admin
        password: 123456
  application:
    name: gateway-zuul

zuul:
  ignored-services: "*"            # 设置忽略的服务，即配置后将不会被路由（但对于明确配置在路由中的，将不会被忽略）
  routes:
    api-test:                       # 基于 ServiceId 的映射（自定义路由的名字）
      path: /test-zuul/**
      serviceId: eureka-producer


eureka:
  port: 9001
  instance:
    hostname: localhost
#客户端
  client:
    healthcheck:
      enabled: true
#注册中心地址
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${eureka.port}/eureka/